name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build \
            -t sstoves/mudlet-vnc:latest \
            -t sstoves/mudlet-vnc:4.21.1 \
            .
          docker push sstoves/mudlet-vnc:4.21.1
          docker push sstoves/mudlet-vnc:latest

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: sstoves/mudlet-vnc
          readme-filepath: ./README.md
